name: Ping Glitch and Force Update

on:
  schedule:
    - cron: '0 9 * * *' # 9:00 AM UTC, diariamente
  workflow_dispatch: # Mantém a opção de execução manual

jobs:
  ping_glitch:
    runs-on: ubuntu-latest

    steps:
    - name: Send request to Glitch site
      run: |
        curl -X GET https://sly-sunset-oxygen.glitch.me/
        sleep 50
        curl -X GET https://sly-sunset-oxygen.glitch.me/force-update-failed-players
